### ISSUE TITLE
What changes should we make for our 5.4 release?

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/r-novice-inflammation#127]
Please use this issue for discussion of changes we should make by mid-August 2015.

**Comment by AnthonyDShaw** [comment]
Would it be possible to make the example data look more like real data without disrupting the lesson material? e.g., sampled from normal distribution with rnorm() command? Would show how tools applicable to users own research more effectively.

**Comment by TomKellyGenetics** [comment]
Would it be possible to make the example data look more like real data without disrupting the lesson material? e.g., sampled from normal distribution with rnorm() command? Would show how tools applicable to users own research more effectively.

**Comment by jdblischak** [comment]
Thanks for the suggestion, @TomKellyGenetics. Could you please expand on your idea? Here are my initial thoughts.

We could generate the data in a different way, but currently we don't cover how the data was generated during the lesson (the data was originally created using this [Python script][py], which we didn't end up transferring to this repo). The narrative of the lesson is that we want to analyze the inflammation results that has data in similar format across multiple files. We build a function to analyze one file and then apply this function to all the data files automatically using a loop. I'm not sure when it would be natural to transition to "Now let's cover how we created this fake data", but I'm open to suggestions.

The main visualizations we create in the lesson are the mean, minimum, or maximum inflammation per day for the duration of the treatment. How were you imagining making these plots look more like real data?

[py]: https://github.com/swcarpentry/python-novice-inflammation/blob/gh-pages/tools/gen_inflammation.py

**Comment by TomKellyGenetics** [comment]
Hi John (@jdblischak),

I think you've misunderstood. I'm proposing working with a different dataset: without significantly changing the lesson materials or covering how it was generated. Although what I've suggested (in R) is very similar to the current python script. Perhaps mean, standard deviation, or quartiles (boxplots) would be more similar to to real biological analysis. Would it be possible to make the data based on a curve rather than a peak?

I understand that the intention here is to focus on the programming rather than the statistics but presenting an accessible example may lead to more post-workshop adoption of programming in research. I understand if you want to stick with what you've got and keep the lessons similar to the Python ones rather than moving into R-specific territory (I don't know how difficult it would be to do more advanced statistics in Python/NumPy). I get what we're doing with building up a function and applying it a number of datasets (which is a fantastic example of how computing can impact research) but many of our participants got lost in the details of the function required for the for loop and if/else lessons and missed the overarching concept.
