### ISSUE TITLE
Reference

### ISSUE THREAD

**Issue by orchid00** [swcarpentry/r-novice-inflammation#139]
Glossary

shape (of an array)
    An array’s dimensions, represented as a vector. For example, a 5×3 array’s shape is (5,3). 
----------------------------------------------
in R should be dim() not shape

**Comment by jdblischak** [comment]
Thanks for the suggestion, @orchid00.

The definition is of the word "shape" as it is used in the section [Manipulating data](https://github.com/swcarpentry/r-novice-inflammation/blob/695afc1b0383d947145f71ca1979886df3c7d1a4/01-starting-with-data.md#manipulating-data). Most of the definitions in the reference are not names of functions.

But I agree that I see R programmers refer to the "dimensions" of an array more often than the "shape" of an array. If you'd like to update both [reference.md](https://github.com/swcarpentry/r-novice-inflammation/blob/gh-pages/reference.md) and [01-starting-with-data.Rmd](https://github.com/swcarpentry/r-novice-inflammation/blob/695afc1b0383d947145f71ca1979886df3c7d1a4/01-starting-with-data.Rmd) to consistently refer to "dimensions" instead of "shape", I'd welcome the Pull Request.

**Comment by jdblischak** [comment]
Fixed by #151.
