### ISSUE TITLE
Sequence of teaching

### ISSUE THREAD

**Issue by dmi3kno** [swcarpentry/r-novice-inflammation#249]
I have a suggestion to Schedule part of the title [page](http://swcarpentry.github.io/r-novice-inflammation/). In my view the flow would be better if "Data types and structures" were introduced earlier in the lesson, however I see the benefit of starting with some practical example. The first six sections of this lesson could look like the following:

1. Introduction to RStudio
2. Analyzing Patient Data
3. Data Types and Structures
4. Addressing Data
5. Reading and Writing CSV Files
6. Understanding Factors

There's quite a bit of overlap between sections 2, 3, 4, so if you would agree to this, I volunteer going through these sections and merging them into only two ("Addressing data" will be dissolved in the other two chapters).

Then the rest of the concepts can be introduced.

**Comment by chendaniely** [comment]
Hi @dmi3kno thanks for your feedback.

This is a larger discussion that we need. @hdashnow .

Just to play devil's advocate. This lesson focuses on the programming side of R.
So functions, conditionals, and scripts are at the forefront of the lesson.
The gapminder lesson and the data carpentry lessons are more geared towards analysis related tasks in R.

Regarding the overlap between sections 2, 3, 4. My only opinion about *not* combining them is that it creates a more explicit TOC for people who have not attended a workshop to navigate to relevant topics.

<hr>

It's difficult to order topics. In an ideal world, we'll learn everything in parallel, but since a linear order is needed, this is what the lesson has evolved to be over time.
However, as an instructor, you are able to swap around lesson order as needed.

**Comment by dmi3kno** [comment]
My argument that sequence of teaching is crucial from pedagogic point of view. If you overwhelm people, they will walk away clueless and will not have the guts to try using R with their own data. We switched entirely to "tidyverse" (introducing ggplot as the first topic) and never looked back. Our workshops are oversubscribed and we have tons of positive feedback from people who go out of classroom and start applying the tools they learned to their own problems.

**Comment by katrinleinweber** [comment]
Hello @dmi3kno :-) You mean [SWC-tidyverse](https://github.com/dmi3kno/SWC-tidyverse), I suppose? Would you be willing to send some of the changes you applied there back here as PRs? I'd be very interested in how "tidy upgrades" to this lesson here would look :-)

**Comment by diyadas** [comment]
I'm closing this issue for now, as the [r-gapminder](http://swcarpentry.github.io/r-novice-gapminder/) lesson focuses on the tidyverse.
