### ISSUE TITLE
using `c()` when specifying a range of numbers

### ISSUE THREAD

**Issue by chendaniely** [swcarpentry/r-novice-inflammation#272]
continuing the conversation from #270

@bbolker @hdashnow @naupaka 

![screenshot from 2017-04-06 15-47-46](https://cloud.githubusercontent.com/assets/5782147/24772728/7c015e36-1ae0-11e7-99e8-546b8389b447.png)

**Comment by bbolker** [comment]
It's really just a (minor) question of which option minimizes cognitive load/maximizes clarity.

- `c(1:5)`: redundant code, but maybe helps people understand (but also learn what I would consider to be slightly suboptimal coding habits)
- `1:5`: the most idiomatic R, I think
- `seq(1,5)` perhaps safest

Adding an explanation is also adding cognitive load/something else to think about.

**Comment by naupaka** [comment]
I agree that this is a minor point in the scheme of things, but: `seq(1,5)` seems most consistent to me in this particular case, especially given that it's used on line 432 already. There are lots of other places in the lessons where numeric vectors are created with `:`, so I'm not worried about folks picking up that syntax elsewhere. Plus, in general, I think it's good for people to use `seq()` more often than they do because, as @bbolker mentioned, it fails appropriately.

**Comment by chendaniely** [comment]
@bbolker so i've been very consious of all the R code I see and write these days.
you're definitely right, i'll send a PR for the colon notation. and have a comment about using `seq` on the side.

I realized just now that I have a habit of using `c` because I usually just assume I'm not going to be doing a straight sequence of numbers... until I type it out.
