### ISSUE TITLE
data directory is empty after 'git clone'

### ISSUE THREAD

**Issue by sluedtke** [swcarpentry/r-novice-inflammation#281]
Hi there, 

is it on purpose that the files in the data directory on not tracked by git? With a `git clone`, the directory is empty and one needs to fetch the files separately. 

It is not the case for the python-novice-inflammation repo.

**Comment by JCSzamosi** [comment]
It appears that the files that should be in data are now in files/r-inflammation-novice-data.zip. This seems bad?

**Comment by katrinleinweber** [comment]
Yes, it's on purpose, and because https://github.com/swcarpentry/r-novice-inflammation/commit/41a7763598956d7b03a3cbb659d37ea488576b3f seems very trustworthy, I for one have no plans of reverting it. Although coherency with the [python lesson](https://github.com/swcarpentry/python-novice-inflammation/tree/gh-pages/data) is a worthy goal as well, the lesson websites are built with language-specific tooling. Which is presumably easier with the new folder structure.

Please feel free to re-open the issue, if your questions are not answered.

cc @gvwilson and @fmichonneau just in case
