### ISSUE TITLE
suggestion: ".mat" to "_mat"

### ISSUE THREAD

**Issue by jasongbragg** [swcarpentry/r-novice-inflammation#294]
I suggest that in lesson https://github.com/swcarpentry/r-novice-inflammation, episode 06-best-practices-R, the following:
"For example, name all matrices something ending in .mat"
be changed to:
"For example, name all matrices something ending in _mat"

This is only a tentative suggestion. The motivation is to avoid encouraging the practice of using dots in object names, except in classes. I am somewhat conflicted, because dots are nice and easy to read. But I thought ".mat" might be confusing on two fronts -- 1. if learners undertake lessons in python at the same time, the use of the dot to call methods might get confusing, and 2. if learners are also taking a matlab class, the ".mat" file extension might be a source of confusion.

**Comment by katrinleinweber** [comment]
Hi @jasongbragg :-) Thanks for putting forth these arguments. I agree as well, so if you send a PR, I'll merge it. Please commit both the changes to the `.Rmd`, and the `.md` files ;-)

**Comment by ErinBecker** [comment]
@katrinleinweber - I think only changes to the .Rmd files are needed. @naupaka - could you please confirm?

**Comment by naupaka** [comment]
Yep, only the `Rmd` files should be changed. The `md` files are overwritten every time the site is rebuilt, so any changes there are overwritten/lost. We just had this discussion over on the gapminder R lessons and added in some code to the style repo (https://github.com/swcarpentry/styles/pull/200) that will build in a warning to the `md` files so people don't accidentally edit them and then have to repeat their work.

Also I am definitely +1 for underscores as separators in lieu of periods. I think that by default the lintr package will flag anything that's not snake_case. I think at least over in r-novice-gapminder we have been encouraging folks to follow the [tidyverse style guide](http://style.tidyverse.org/syntax.html#object-names).

**Comment by katrinleinweber** [comment]
Ah, thanks! I edited both several times, but in the same way. Should `_episodes` be `.gitignore`'d then? I could add that to #318.

**Comment by naupaka** [comment]
Yeah, it seems like that would be a good solution. Unfortunately, we can't do that, because the files have to get rendered locally by the maintainers from Rmd to md, and then pushed to GitHub where Jekyll takes the markdown and makes the html. Plus the `.gitignore` won't have any effect on already-tracked files, which all of these are. It's not the best system, because it's confusing for many contributors, but it's the best way we've figured out that allows us to use Rmd with Jekyll. 

One thing we just recently added in is a txt file warning in the `_episodes` directory to let contributors know not to edit the md files in there, since they'll get overwritten: https://github.com/swcarpentry/r-novice-gapminder/pull/340

**Comment by katrinleinweber** [comment]
OK, but it is an actual problem if they do? As far as I understand the workflow currently, it just moves the `.md` changes from a maintainer's catch-all-"render site"-commit to the individual contributions.

So, if people accidentally contribute to a `.md` only, I would ask them to mirror the change to the `.Rmd`, but not ask them to revert it.

**Comment by naupaka** [comment]
RIght, not a problem if you catch it, just potentially frustrating for new contributors to have to redo work.
