### ISSUE TITLE
convert "here" links to useful snippets

### ISSUE THREAD

**Issue by katrinleinweber** [swcarpentry/r-novice-inflammation#331]
[Berkeley's Web Accessibility guide](https://webaccess.berkeley.edu/ask-pecan/click-here) recommends against link texts like "Click `here` to read about our..." and suggests making them more descriptive: "..., read `About Us`". This helps screen reader users esp.

There are several instances of such links that could be converted accordingly.

**Comment by AnthonyDShaw** [comment]
I have begun converting links in my own fork to meet these standards and will push them once they are done, but I have noticed that there are many glossary links, where a single word or concept (like String) has a link to the glossary.
Is it suitable to leave these glossary links to stay as they are, or should they perhaps have an annotation? E.g. the String link might instead become the String (Glossary) link.

**Comment by katrinleinweber** [comment]
Hi Anthony, and thanks for working on this :-)

I suggest to leave glossary links as they are for now. I'm looking forward to reviewing your PR with the new link texts. Feel free to open it already. Cheers!

**Comment by AnthonyDShaw** [comment]
Hi @katrinleinweber , I was going to make a pull request, but after reading the guidelines "[SWC] would like substantial changes to be raised in an issue for input from maintainers before [I] work on a PR"

I am unsure if that counts in this context since I was going to make a pull request in response to your issue, but just in case I will instead link my own repository with the changes for commenting first. Or should I make a new issue instead?

https://github.com/AnthonyDShaw/r-novice-inflammation/tree/gh-pages/_episodes

**Comment by katrinleinweber** [comment]
Updating some phrases are not "substantial changes" IMHO. Since a PR has built-in review features, I find that most effective ;-)

**Comment by diyadas** [comment]
Thanks for your work on this Anthony!

I just wanted to chime in and mention that it is the Rmd files that should be edited and committed, not markdown files directly, since the markdown is generated from the R markdown.  I'll tweak the contribution guidelines a bit to make this (and PRs vs. issues) clearer.

**Comment by katrinleinweber** [comment]
Whoa, sorry for missing that! I thought #359 would prevent this from happening again.

**Comment by Bisaloo** [comment]
I reviewed the code and couldn't find any occurences at this time.

Additionally, the new workbench infrastructure, and [`pegboard::validate_links()`](https://carpentries.github.io/pegboard/reference/validate_links.html) will now check that all links are associated with descriptive text:

https://github.com/carpentries/pegboard/blob/1bc5753e917d515c3d888ce6cc013c0a680eacfc/R/validate_links.R#L171-L188

Closing this issue. Thanks everyone for your work on this!
