### ISSUE TITLE
Logo proposal

### ISSUE THREAD

**Issue by baranpirincal** [swcarpentry/r-novice-inflammation#352]
Hey, I saw that your project has no logo design. If you interested, I can contribute on your project with making a logo design. My purposes are supporting open source projects and make my portfolio better. I am waiting your feedback. Have a nice day!

Best Regards,
Baran Pirincal
Visual Communication Designer

**Comment by katrinleinweber** [comment]
Hi Baran,

since no other Carpentry lesson has its own logo, and [The Carpentries organisation had a new one made recently](https://software-carpentry.org/blog/2018/02/our-new-logo.html), I think we are good here.

You could ask the coordinators over in https://github.com/swcarpentry/lesson-example/issues whether they would generally support the idea of logos for each lesson. cc @rgaiacs

Nonetheless, thank you for your offer and kind regards,
Katrin Leinweber
Lesson Maintainer
