### ISSUE TITLE
In the Rescaling challange, formulas are not rendered

### ISSUE THREAD

**Issue by katrinleinweber** [swcarpentry/r-novice-inflammation#363]
http://swcarpentry.github.io/r-novice-inflammation/02-func-R/#rescaling

> If $L$ and $H$ are the lowest and highest values in the original vector, then the replacement for a value $v$ should be $(v-L) / (H-L)$.

I tried 4 different browsers, with JavaScript on, ad-blocker off, etc. There seems to be a bug in our publishing scripts. I checked whether they render in the 2-years-old e7f332475a67987fb726b9457772d9f7067f09f0, but they don't. Do they for anyone else?

Maybe related to #154?

**Comment by diyadas** [comment]
It doesn't render for me either.

**Comment by katrinleinweber** [comment]
Time to call the cavalry :-D @rgaiacs: Do you know what has caused this? I tried `git bisect` and `make serve`, but before I found the bad commit, I got back to a time before there was a `Makefile`. Then I wasn't sure any more how to test whether that formulae rendered.

**Comment by rgaiacs** [comment]
> Do you know what has caused this?

We don't include MathJax into the styles. For details, see https://github.com/carpentries/styles/issues/154.

I understand that styling the variables/letters like in math textbooks would be great but we not writing complex math so I prefer that we avoid the inclusion of MathJax so that the page load faster for users. The quoted section could be rewrite without lost it meaning like

~~~
If `L` and `H` are the lowest and highest values in the original vector, then the replacement for a value `v` should be `(v-L) / (H-L)`.
~~~

**Comment by katrinleinweber** [comment]
OK, thanks for the info and suggestion :-)
