### ISSUE TITLE
Clarify repo purpose and contributions

### ISSUE THREAD

**Issue by diyadas** [swcarpentry/r-novice-inflammation#401]
I brought up this lesson during the R-Ladies SF meetup on contributing to OSS projects on GitHub, and it turns out that people might find it really confusing if they landed on our page by "browsing GitHub," vs. coming through the Carpentries. I did not have this issue because I was directed to this repo by the Carpentries, but it's not immediately clear that our repo is for a website (unless people know where to look) and most issues as filed don't directly link to the issue in question - potential new contributors have to be very clear on what "episodes" are and where the issue is.

Can we change:
1. The description (not changeable by us maintainers but something to send upward): "Repo creates a website for the Software Carpentry introduction to R for novices using inflammation data" 
2. Change the beginning of the README to specify that this repo generates the lesson website (and link to the lesson again!)
3. Change the issue template to ask that people link to the episodes, so that when we tag "good first issue" new contributors know where to start (??) ... or we could do this as maintainers in our response to issues - I think @katrinleinweber already does though I haven't :(

Thoughts? (thanks to @gdequeiroz for bringing this up)

**Comment by katrinleinweber** [comment]
Agreed. I'm guessing @rgaiacs can update the description. Let's try something that ends in `website:` though, so that the link up there gets more attention.

**Comment by rgaiacs** [comment]
> The description (not changeable by us maintainers but something to send upward): "Repo creates a website for the Software Carpentry introduction to R for novices using inflammation data"

The new description looks good to me. But I can't change. @fmichonneau is the person in charge of the descriptions.

> Change the beginning of the README to specify that this repo generates the lesson website (and link to the lesson again!)

Good suggestion. @fmichonneau is in charge of changes like this.

> Change the issue template to ask that people link to the episodes, so that when we tag "good first issue" new contributors know where to start (??) ... or we could do this as maintainers in our response to issues - I think @katrinleinweber already does though I haven't :(

Another great suggestion. Pull request to https://github.com/carpentries/styles changing https://github.com/carpentries/styles/tree/gh-pages/.github is very welcome.

**Comment by anacost** [comment]
Hi @diyadas 
we have updated the style in
https://github.com/carpentries/styles/pull/395
Maybe this helps with this issue.
Do you have suggestions?

**Comment by katrinleinweber** [comment]
TBH, I think we have [too](https://github.com/carpentries/styles/blob/gh-pages/bin/boilerplate/README.md#contributing) [many](https://github.com/carpentries/styles/blob/gh-pages/bin/boilerplate/CONTRIBUTING.md#how-to-contribute) [different](https://carpentries.github.io/lesson-example/) places in which contribution advice is given. [Pro Git](https://git-scm.com/book/en/v2/GitHub-Contributing-to-a-Project) has out-of-date screenshots and is otherwise also not ideal for our learners. If it was, we wouldn't need a git-novice lesson. [GitHub flow](https://guides.github.com/introduction/flow/) is intended for project maintaners. Because it doesn't mention forking, it can easily cause confusion.

What do you think about cutting all that fat and refering only to https://opensource.guide/how-to-contribute/#opening-a-pull-request or another GitHub-endorsed guide. The `Where...`, `What... ` & `What not...` sections are reasonably unique to the Carpentries to keep them, of course.

**Comment by anacost** [comment]
hi @katrinleinweber , 
great comments! Would you like to propose an update on this part to the style?

**Comment by diyadas** [comment]
Hi @fmichonneau would you be able to change the description on this repo to something like: 
"Repo creates a website for the Software Carpentry introduction to R for novices using inflammation data: "

That's the last item outstanding here - all the other suggestions have been implemented, thanks all.

**Comment by fmichonneau** [comment]
I updated the description as suggested. Does this look OK?

**Comment by diyadas** [comment]
It looks great! Thank you.
