### ISSUE TITLE
Error in loop exercise setup - 'making choices' lesson?

### ISSUE THREAD

**Issue by orb16** [swcarpentry/r-novice-inflammation#404]
In the exercise "find the maximum inflammation score" in the lesson "Making choices" http://swcarpentry.github.io/r-novice-inflammation/04-cond/index.html the inner loop reads

`for(patient_index in length(dat.means))`
This is supposed to iterate over all patients in each file; but you would either need to use
`1:length(dat.means)`
or alternatively (and what I would suggest):
`for(patient_index in seq_along(dat.means)`

Otherwise all you do is assess the last patient in each dataframe (as visible when you use `print(patient_index)` during the loop).

**Comment by katrinleinweber** [comment]
Thanks for alerting us of this problem, @orb16 :-) Since `seq_along` is explained in [15-supp-loops-in-depth](https://swcarpentry.github.io/r-novice-inflammation/15-supp-loops-in-depth/index.html), and because it's a smaller step over what the previous episodes already included, I choose the  `1:` notation.
