### ISSUE TITLE
Loops in R ,  RStudio

### ISSUE THREAD

**Issue by Ahmed7emdan** [swcarpentry/r-novice-inflammation#449]
Hi,
A.
I would say the illustration of Loops in R  brought us from the basic loop constructs used in programming to the fundamental idea behind vectorization. Therefore, I would just suggest due to time constrains
adding just simple example of the use of one of the apply() family of functions, which come up frequently in R. 
Adding a line about mapply()  Multivariate version of lapply + split function to already existing apply ()family.
In terms of code flow control, Should we give a hint about the methods in the code?.
B.
What do you think if we to talk about " Introduction to RStudio" session at first then code through it accordingly? 
Cheers,

**Comment by katrinleinweber** [comment]
Hi Ahmed! Welcome to the Carpentries :-)

We have [1 `apply` example already, repeated a few times across the episodes](https://github.com/swcarpentry/r-novice-inflammation/search?l=RMarkdown&q=apply). What do you think about it?

Because [we already discussed](https://github.com/swcarpentry/r-novice-inflammation/issues/250#issuecomment-289682352) adding [`purrr::map()`](https://resources.rstudio.com/wistia-rstudio-conf-2017/happy-r-users-purrr-tutorial-charlotte-wickham), I would advise against adding content about `mapply()`.

About your point B.: I'm pretty sure most instructors do introduce RStudio 1st. Since moving all the files around complicates digging through [Git's blame history](https://www.atlassian.com/git/tutorials/inspecting-a-repository/git-blame), I would also advise against reordering the files.

Kind regards :-)

**Comment by jacquelyneneal** [comment]
Hi! I was reading through this and am curious and a little confused - would all of the code using `mapply` be replaced with the `purrr` setup, or would you want to use both side by side? I didn't see a reference to `purrr` in the lesson, but I could have missed it.

I've used both in different situations - are there advantages to using one over the other beyond the nice feature of `purrr` fitting with all tidyverse?

**Comment by katrinleinweber** [comment]
> side by side?

My vote is definitely for only one possibility. Not sure about the pros & cons, TBH.

Let's continue this discussion in https://github.com/swcarpentry/r-novice-inflammation/issues/250#issuecomment-289682352 only.
