### ISSUE TITLE
Episode 4 and 5: Function Error

### ISSUE THREAD

**Issue by MichaelBAnderson** [swcarpentry/r-novice-inflammation#456]
Dear All,

I believe I found an issue.  At the end of Episode 4 and in Episode 5 we are instructed on two important functions: "analyze" and "analyze_all"

The **analyze** function opens a file based on the filename and plots the mean, max and min for the columns, and works as expected.  The **analyze_all** function is not working (at-least for me):

`analyze_all <- function(folder = "data", pattern) {`
 `filenames <- list.files(path = folder, pattern = pattern, full.names = TRUE)`
 `for (f in filenames) {`
`    analyze(f)`
`  }`
`}`

The error message is helpful because it indicates the problem has to do with identifying filenames by their string pattern (pattern = pattern).  To fix, the second pattern can be changed to "inflammation.*csv" (pattern = "inflammation.*csv").

I am planning to do a pull-request for episode 5 after my demo this Thursday so I will add this to that.  If I am wrong about my understanding of the episode, please let me know.

Thanks,

-Michael

**Comment by MichaelBAnderson** [comment]
I am new to doing the pull requests and have just completed my first (about the command line program location for saving/storing scripts).  I am waiting to begin a pull request here to see how the first request is resolved.  If it is possible I would also like to know if anyone else had a problem with the analyze_all function.  I had to change (pattern = pattern) to (pattern - inflammation.*csv) for it to work.  But it seems strange that it has not been fixed before now, since it is an important function that is used over and over again.  

Can anyone confirm that this is indeed an issue?

If, so, I will fix and push it.

Thanks,

-Michael

**Comment by Bisaloo** [comment]
Hi @MichaelBAnderson, I know this answer comes very late after your report but here my understanding:

The `analyze_all()` function is correct.

https://github.com/swcarpentry/r-novice-inflammation/blob/fbf232bd12a5e3260eb183061414ac5a7f7ebc0c/episodes/04-cond.Rmd#L49-L56

But you are right that if you try to call it directly with `analyze_all()`, you will the following error:

> Error in analyze_all() : argument "pattern" is missing, with no default

This is not a bug but expected behaviour. The function `analyze_all()` has a `pattern` argument without a default value, and no value has been passed.

To call this function, you would need to call `analyze_all(pattern = inflammation.*csv)` and the pattern argument will be forwarded correctly to `list.files()`.

I have opened https://github.com/swcarpentry/r-novice-inflammation/pull/626 to clarify this point. If you have a moment, a review would be greatly appreciated but no pressure. I understand you may have moved on to other things.
