### ISSUE TITLE
Running "make serve" to create local html lessons

### ISSUE THREAD

**Issue by strajanoski** [swcarpentry/r-novice-inflammation#477]
Dear community,

as I was working on Issue #472 in the testing procedure I wanted to create html lessons out of the rmd files to check the output. I managed to setup everything (fork, clone, new branch, new ruby version, jeckyll etc.), but I get error message with jekyll serve (last step in the process) throwing following error message:
jekyll serve
Traceback (most recent call last):
	4: from /Users/zaki/.rvm/gems/ruby-2.7.0/bin/ruby_executable_hooks:24:in `<main>'
	3: from /Users/zaki/.rvm/gems/ruby-2.7.0/bin/ruby_executable_hooks:24:in `eval'
	2: from /Users/zaki/.gem/ruby/2.7.0/bin/jekyll:23:in `<main>'
	1: from /Users/zaki/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/rubygems.rb:294:in `activate_bin_path'
/Users/zaki/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/rubygems.rb:275:in `find_spec_for_exe': can't find gem jekyll (>= 0.a) with executable jekyll (Gem::GemNotFoundException)
make: *** [serve] Error 1
According to some forums the error arises when gem or bundle folder are missing, but I suppose I'm doing something wrong.
I'm using Mac OS Mojave 10.14.
Thank you very much in advance.

Regards,
Slave

**Comment by zkamvar** [comment]
Hi @strajanoski, if you have docker installed on your machine, you might want to give our docker container for lessons a try: https://github.com/carpentries/lesson-docker/#readme

**Comment by Bisaloo** [comment]
Thanks for the report! 

This issue is related to the previous version of our lesson infrastructure. We have since then moved in a different direction, which will hopefully prove easier to use (thanks to Zhian's amazing work!).

A solid overview of the infrastructure is available [on the official Carpentries Workbench documentation website](https://carpentries.github.io/workbench/).

I'm closing this issue but please open a new one if you have any questions or issues with the workbench.
