### ISSUE TITLE
Add a section about NA values in tests

### ISSUE THREAD

**Issue by Bisaloo** [swcarpentry/r-novice-inflammation#511]
In the [Making Choices](https://swcarpentry.github.io/r-novice-inflammation/04-cond/index.html), I think it would be extremely valuable to add a section / a note / a box about how to test for the presence of `NA`s with `is.na()`:

- It is a very common source of confusion and errors for beginners and the error message is not easy to understand:

``` r
a <- NA 

a == NA
#> [1] NA

if (a == NA) {
  print("Hi!")
}
#> Error in if (a == NA) {: missing value where TRUE/FALSE needed
```

<sup>Created on 2021-04-13 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0.9002)</sup>

- A similar note is already present about testing for `NULL` values with `is.null()`

- `NA` values have already been introduced in the previous lesson about `for` loops

If you think this would be a worthwhile addition, I'm happy to submit a PR for it.

**Comment by HaoZeke** [comment]
I'd love to see this as a PR! Its something I end up describing in most cases as well. I'm personally against using `NULL` in scripts (anything which isn't a package) because its semantics are different from what learners expect, but removing it should be a different issue.

In any case, the `NA` note would be fantastic.
