### ISSUE TITLE
No jumplinks for section headings

### ISSUE THREAD

**Issue by annajiat** [swcarpentry/r-novice-inflammation#532]
@zkamvar
We need to update style for this lesson so that jump lists (anchors for different sections) becomes automatically available for different levels of headings.

**Comment by Bisaloo** [comment]
Thanks for the report! This issue is now solved as far as I can tell and we can get direct links to any level of heading. Some examples:

https://swcarpentry.github.io/r-novice-inflammation/12-supp-factors.html#adjusting-factor-levels

https://swcarpentry.github.io/r-novice-inflammation/04-cond.html#conditionals

I'm therefore closing this issue. Please let me know if this is not fully addressing your needs :pray:
