### ISSUE TITLE
the use of spaces in subsetting

### ISSUE THREAD

**Issue by aurielfournier** [swcarpentry/r-novice-inflammation#78]
I proposed some changes to the subsetting lesson and included spaces that are not part of the Google R Style Guide, and so it was requested I remove them, which I did. After some discussion with Karl Broman I wanted to suggest that for the purposes of teaching we should not follow the style guide in this respect. 

When I teach my peers subsetting in R I always tell them to put in spaces when they want all the rows or all the columns

THIS -> dataframe[ ,5] 

instead of this -> dataframe[,5]

I talked to them about thinking when they type that first bracket 'do I want all the rows?" if yes, then put a space, then a comma, then whatever you want for the columns (or vise versa, put in your subsetting stuff for the rows and then ask if you want all the columns, if yes, put a space). 

I've found this helpful because it forces the learner to think about what is being indicated on both sides of the comma and helps prevent confusion about what goes where. Overtime perhaps the learner doesn't need to do it, I still do, but they may not, but I think it is a good learning tool. 

I realize its not with the style guide, but I think it is worth considering and some of you won't like this, but that is how I plan to teach. 

*ducks from all the angry people throwing things*

**Comment by jdblischak** [comment]
The lessons follow a style guide for the sake of consistency, not because one way is necessarily better than another way. When teaching the material live, you can use whatever style you like as long as you use it consistently. But when collaboratively developing a lesson, we need some guide otherwise the style would randomly change as each new edit was made by a different person.

Your PR #69 has still not been updated. Maybe you updated them locally but never pushed? Please let me know if you need help with this.

In general, if you want to start a broad conversation about a given topic in R, your best option is to send your message to the [r-discuss](http://lists.software-carpentry.org/mailman/listinfo/r-discuss_lists.software-carpentry.org) list.
